name: LeetCode Report Generator

on:
  push:
    paths:
      - 'data/solved.csv'
      - 'leetcode_report.py'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pandas
      run: pip install pandas

    - name: Run report script
      run: python leetcode_report.py

    - name: Commit generated report
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add report.md
        git commit -m "📈 update report" || echo "No changes"
        git push
